name: Example  Snyk testing
on:
  push:
    branches:
      - feature/*
      - fix/*


jobs:
  security:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
       
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
